nav:
  Tôi: /about/
bottom_nav:
  Home: /
  Tôi: /about/
  Người Ta: http://devnhanguoita.com

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/hienvd.png
        gravatar: false
    favicon:
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        twitter: http://twitter.com/duchienvuong
        facebook: http://facebook.com/hienkhongdeu
    show_all_posts: true
    post_count: 5
    highlight: monokai

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: hienvuongblog
    google_analytics: UA-76642041-1

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
